/** 常用国家/地区代码 -> 中文名（ISO 3166-1 alpha-2） */
export const COUNTRY_NAMES: Record<string, string> = {
  SG: '新加坡',
  US: '美国',
  JP: '日本',
  HK: '中国香港',
  TW: '中国台湾',
  MO: '中国澳门',
  CN: '中国大陆',
  KR: '韩国',
  GB: '英国',
  DE: '德国',
  FR: '法国',
  NL: '荷兰',
  RU: '俄罗斯',
  CA: '加拿大',
  AU: '澳大利亚',
  NZ: '新西兰',
  IN: '印度',
  ID: '印度尼西亚',
  MY: '马来西亚',
  TH: '泰国',
  VN: '越南',
  PH: '菲律宾',
  KH: '柬埔寨',
  LA: '老挝',
  MM: '缅甸',
  BD: '孟加拉国',
  PK: '巴基斯坦',
  LK: '斯里兰卡',
  NP: '尼泊尔',
  KZ: '哈萨克斯坦',
  TR: '土耳其',
  AE: '阿联酋',
  SA: '沙特阿拉伯',
  QA: '卡塔尔',
  KW: '科威特',
  BH: '巴林',
  OM: '阿曼',
  IL: '以色列',
  IR: '伊朗',
  IQ: '伊拉克',
  JO: '约旦',
  EG: '埃及',
  ZA: '南非',
  NG: '尼日利亚',
  KE: '肯尼亚',
  MA: '摩洛哥',
  TN: '突尼斯',
  DZ: '阿尔及利亚',
  ET: '埃塞俄比亚',
  GH: '加纳',
  IT: '意大利',
  ES: '西班牙',
  PT: '葡萄牙',
  CH: '瑞士',
  AT: '奥地利',
  BE: '比利时',
  LU: '卢森堡',
  IE: '爱尔兰',
  IS: '冰岛',
  SE: '瑞典',
  NO: '挪威',
  DK: '丹麦',
  FI: '芬兰',
  PL: '波兰',
  CZ: '捷克',
  SK: '斯洛伐克',
  HU: '匈牙利',
  RO: '罗马尼亚',
  BG: '保加利亚',
  GR: '希腊',
  UA: '乌克兰',
  BY: '白俄罗斯',
  MD: '摩尔多瓦',
  RS: '塞尔维亚',
  HR: '克罗地亚',
  SI: '斯洛文尼亚',
  BA: '波黑',
  MK: '北马其顿',
  AL: '阿尔巴尼亚',
  EE: '爱沙尼亚',
  LV: '拉脱维亚',
  LT: '立陶宛',
  GE: '格鲁吉亚',
  AM: '亚美尼亚',
  AZ: '阿塞拜疆',
  MX: '墨西哥',
  BR: '巴西',
  AR: '阿根廷',
  CL: '智利',
  CO: '哥伦比亚',
  PE: '秘鲁',
  VE: '委内瑞拉',
  UY: '乌拉圭',
  PY: '巴拉圭',
  BO: '玻利维亚',
  EC: '厄瓜多尔',
  CR: '哥斯达黎加',
  PA: '巴拿马',
  GT: '危地马拉',
  DO: '多米尼加',
  PR: '波多黎各',
  CU: '古巴',
  JM: '牙买加',
  FJ: '斐济',
  PG: '巴布亚新几内亚',
  MN: '蒙古',
  UZ: '乌兹别克斯坦',
  KG: '吉尔吉斯斯坦',
  TJ: '塔吉克斯坦',
  TM: '土库曼斯坦',
  AF: '阿富汗',
  BN: '文莱',
  TL: '东帝汶',
  MV: '马尔代夫',
  BT: '不丹',
  CY: '塞浦路斯',
  MT: '马耳他',
  MC: '摩纳哥',
  LI: '列支敦士登',
  AD: '安道尔',
  SM: '圣马力诺',
};

/** 返回中文名，未知代码回退为代码本身 */
export function countryName(cc: string): string {
  return COUNTRY_NAMES[cc.toUpperCase()] ?? cc.toUpperCase();
}

/** 供多选组件使用的列表（常用地区在前） */
export const COUNTRY_OPTIONS: { code: string; name: string }[] = Object.entries(
  COUNTRY_NAMES,
).map(([code, name]) => ({ code, name }));
